### ISSUE TITLE
UTF8 is not a function

### ISSUE THREAD

**Issue by xevidos** [webtorrent/bittorrent-peerid#16]
The error is below.

I am running:
ubuntu 16.04
node v4.2.6
npm 3.5.2

sudo bittorrent-tracker
HTTP tracker: http://localhost:8000/announce
UDP tracker: udp://0.0.0.0:8000
UDP6 tracker: udp://localhost:8000
WebSocket tracker: ws://localhost:8000
Tracker stats: http://localhost:8000/stats
WARNING: invalid action in HTTP request: /favicon.ico
start: 192.168.1.1:30018
start: 192.168.1.1:51413
/usr/local/lib/node_modules/bittorrent-tracker/node_modules/bittorrent-peerid/index.js:15
    buffer = Buffer.from(peerId, 'utf8')
                    ^

TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at module.exports (/usr/local/lib/node_modules/bittorrent-tracker/node_modules/bittorrent-peerid/index.js:15:21)
    at /usr/local/lib/node_modules/bittorrent-tracker/server.js:236:39
    at Array.forEach (native)
    at /usr/local/lib/node_modules/bittorrent-tracker/server.js:209:16
    at Array.forEach (native)
    at Server.<anonymous> (/usr/local/lib/node_modules/bittorrent-tracker/server.js:204:20)
    at emitTwo (events.js:92:20)
    at Server.emit (events.js:172:7)

**Comment by DiegoRBaquero** [comment]
https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding was added in node v5.1, please update to Node v8 LTS (currently 8.9.1)
